version: 2.1

jobs:
  test:
    docker:
<<<<<<< HEAD
      - image: cimg/node:14.20
=======
      - image: cimg/node:18.20.2
>>>>>>> 0757e71 (Add CircleCI config to run Jest tests)
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
